time ./manualCalib.py > calibStage5-10Reads_1.txt
time ./manualCalib.py > calibStage5-10Reads_2.txt
time ./manualCalib.py > calibStage5-10Reads_3.txt
time ./manualCalib.py > calibStage5-10Reads_4.txt
time ./manualCalib.py > calibStage5-10Reads_5.txt
time ./manualCalib.py > calibStage5-10Reads_6.txt
time ./manualCalib.py > calibStage5-10Reads_7.txt
time ./manualCalib.py > calibStage5-10Reads_8.txt
time ./manualCalib.py > calibStage5-10Reads_9.txt
time ./manualCalib.py > calibStage5-10Reads_10.txt
time ./manualCalib.py > calibStage5-10Reads_11.txt
time ./manualCalib.py > calibStage5-10Reads_12.txt
time ./manualCalib.py > calibStage5-10Reads_13.txt
time ./manualCalib.py > calibStage5-10Reads_14.txt
time ./manualCalib.py > calibStage5-10Reads_15.txt
time ./manualCalib.py > calibStage5-10Reads_16.txt
time ./manualCalib.py > calibStage5-10Reads_17.txt
time ./manualCalib.py > calibStage5-10Reads_18.txt
time ./manualCalib.py > calibStage5-10Reads_19.txt